#ifndef BLADE_PIPELINES_ATA_MODE_B_CONFIG_H
#define BLADE_PIPELINES_ATA_MODE_B_CONFIG_H

#define BLADE_INPUT_NANT 20
#define BLADE_INPUT_NCOMPLEX_BYTES 2

#define BLADE_ANT_NCHAN 192
#define BLADE_NTIME 8192
#define BLADE_NPOL 2

#define BLADE_OUTPUT_NBEAM 8
#define BLADE_OUTPUT_NCOMPLEX_BYTES 4

#if BLADE_OUTPUT_NCOMPLEX_BYTES == 8
	#define BLADE_OUTPUT_ELEMENT_T CF32
#else
	#define BLADE_OUTPUT_ELEMENT_T CF16
#endif

#endif